# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formtemplate.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTemplate(object):
    def setupUi(self, FormTemplate):
        FormTemplate.setObjectName("FormTemplate")
        FormTemplate.resize(817, 842)
        self.centralwidget = QtWidgets.QWidget(FormTemplate)
        self.centralwidget.setObjectName("centralwidget")
        self.form_image = QtWidgets.QLabel(self.centralwidget)
        self.form_image.setGeometry(QtCore.QRect(0, 0, 541, 791))
        self.form_image.setFrameShape(QtWidgets.QFrame.Panel)
        self.form_image.setFrameShadow(QtWidgets.QFrame.Plain)
        self.form_image.setText("")
        self.form_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.form_image.setObjectName("form_image")
        self.add_field_object = QtWidgets.QPushButton(self.centralwidget)
        self.add_field_object.setGeometry(QtCore.QRect(680, 640, 89, 25))
        self.add_field_object.setObjectName("add_field_object")
        self.field_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.field_line_edit.setGeometry(QtCore.QRect(550, 640, 121, 25))
        self.field_line_edit.setObjectName("field_line_edit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(550, 0, 251, 431))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(121)
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setEnabled(True)
        self.removeButton.setGeometry(QtCore.QRect(550, 440, 251, 25))
        self.removeButton.setObjectName("removeButton")
        self.radio_single_line = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_single_line.setGeometry(QtCore.QRect(550, 580, 112, 23))
        self.radio_single_line.setChecked(True)
        self.radio_single_line.setObjectName("radio_single_line")
        self.radio_paragraph = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_paragraph.setGeometry(QtCore.QRect(550, 610, 112, 23))
        self.radio_paragraph.setObjectName("radio_paragraph")
        FormTemplate.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FormTemplate)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 22))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuTemplate = QtWidgets.QMenu(self.menubar)
        self.menuTemplate.setObjectName("menuTemplate")
        FormTemplate.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FormTemplate)
        self.statusbar.setObjectName("statusbar")
        FormTemplate.setStatusBar(self.statusbar)
        self.actionLoadImage = QtWidgets.QAction(FormTemplate)
        self.actionLoadImage.setObjectName("actionLoadImage")
        self.actionSave_Template = QtWidgets.QAction(FormTemplate)
        self.actionSave_Template.setObjectName("actionSave_Template")
        self.actionExit = QtWidgets.QAction(FormTemplate)
        self.actionExit.setObjectName("actionExit")
        self.actionNew = QtWidgets.QAction(FormTemplate)
        self.actionNew.setObjectName("actionNew")
        self.actionLoadTemplate = QtWidgets.QAction(FormTemplate)
        self.actionLoadTemplate.setObjectName("actionLoadTemplate")
        self.actionSaveTemplate = QtWidgets.QAction(FormTemplate)
        self.actionSaveTemplate.setObjectName("actionSaveTemplate")
        self.actionStart = QtWidgets.QAction(FormTemplate)
        self.actionStart.setObjectName("actionStart")
        self.menuFIle.addAction(self.actionNew)
        self.menuFIle.addAction(self.actionLoadImage)
        self.menuFIle.addAction(self.actionExit)
        self.menuRun.addAction(self.actionStart)
        self.menuTemplate.addAction(self.actionLoadTemplate)
        self.menuTemplate.addAction(self.actionSaveTemplate)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuTemplate.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())

        self.retranslateUi(FormTemplate)
        QtCore.QMetaObject.connectSlotsByName(FormTemplate)

    def retranslateUi(self, FormTemplate):
        _translate = QtCore.QCoreApplication.translate
        FormTemplate.setWindowTitle(_translate("FormTemplate", "MainWindow"))
        self.add_field_object.setText(_translate("FormTemplate", "Add Field"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormTemplate", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormTemplate", "Type"))
        self.removeButton.setText(_translate("FormTemplate", "Remove"))
        self.radio_single_line.setText(_translate("FormTemplate", "Single Line"))
        self.radio_paragraph.setText(_translate("FormTemplate", "Paragraph"))
        self.menuFIle.setTitle(_translate("FormTemplate", "File"))
        self.menuRun.setTitle(_translate("FormTemplate", "Run"))
        self.menuTemplate.setTitle(_translate("FormTemplate", "Template"))
        self.actionLoadImage.setText(_translate("FormTemplate", " Load Image"))
        self.actionSave_Template.setText(_translate("FormTemplate", "Save"))
        self.actionExit.setText(_translate("FormTemplate", "Exit"))
        self.actionNew.setText(_translate("FormTemplate", "New"))
        self.actionLoadTemplate.setText(_translate("FormTemplate", "Load Template"))
        self.actionSaveTemplate.setText(_translate("FormTemplate", "Save Template"))
        self.actionStart.setText(_translate("FormTemplate", "Start"))


